apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-component
  name: test-component
  labels:
    app: test-component
spec:
  selector:
    matchLabels:
      app: test-component
  template:
    metadata:
      labels:
        app: test-component
        name: test-component
    spec:
      containers:
        - name: test-component
          image: srinath-intelops/srinath/test-component
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 9995
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        